version: '3'

services:
  redis:
    image: redis

  django:
    container_name: django
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./celery:/app/
    ports:
      - 8001:8000

    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./
    command: ["celery", "--app=celery", "worker", "-l", "INFO"]
    # celery --app=celery worker -l INFO

    volumes:
      - ./celery:/app/
    depends_on:
      - redis

