version: '3'

services:

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL =amqp://guest:guest@rabbitmq:5673

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"



  redis:
    image: redis

  django:
    container_name: django
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./celery:/app/
    ports:
      - 8001:8000

    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./
    command: celery -A settings worker --hostname=celeryWorker1@%h -l INFO -Q tasks
    # celery,celery:1,celery:2,celery:3
    # queue1
    volumes:
      - ./celery:/app/
    depends_on:
      - django
      - redis
      - rabbitmq

  # celery2:
  #   container_name: celery2
  #   build:
  #     context: ./celeryworker
  #     dockerfile: Dockerfile
  #   command: celery -A celerytask worker -l INFO -Q queue2
  #   volumes:
  #     - ./celeryworker:/app/
  #   depends_on:
  #     - django
  #     - redis

    # celery worker --app=celery --loglevel=info
    # celery --app=celery worker -l INFO