version: '3'

services:
  redis:
    image: redis

  django:
    container_name: django
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./celery:/app/
    ports:
      - 8001:8000

    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./
    command: celery -A settings worker -l INFO -Q queue1
    volumes:
      - ./celery:/app/
    depends_on:
      - django
      - redis

  celery2:
    container_name: celery2
    build:
      context: ./celeryworker
      dockerfile: Dockerfile
    command: celery -A celerytask worker -l INFO -Q queue1
    volumes:
      - ./celeryworker:/app/
    depends_on:
      - django
      - redis

    # celery worker --app=celery --loglevel=info
    # celery --app=celery worker -l INFO